config/routes.rb
Rails.application.routes.draw do
  resources :magentos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/magento.rb
class Magento < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/magentos_controller.rb
class MagentosController < ApplicationController

  # GET /magentos
  # GET /magentos.json
  def index
    @auth_hash = request.env['omniauth.auth']
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/magentos_helper.rb
module MagentosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Omniauthapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/magentos/_form.html.erb
<%= form_with(model: magento, local: true) do |form| %>
  <% if magento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(magento.errors.count, "error") %> prohibited this magento from being saved:</h2>

      <ul>
      <% magento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/magentos/edit.html.erb
<h1>Editing Magento</h1>

<%= render 'form', magento: @magento %>

<%= link_to 'Show', @magento %> |
<%= link_to 'Back', magentos_path %>

app/views/magentos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Magentos</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td>AUTH HASH <%= @auth_hash %></td>
      </tr>
  </tbody>
</table>

<br>

app/views/magentos/new.html.erb
<h1>New Magento</h1>

<%= render 'form', magento: @magento %>

<%= link_to 'Back', magentos_path %>

app/views/magentos/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_magento_path(@magento) %> |
<%= link_to 'Back', magentos_path %>